package com.rndcs.artificialintelligence;
import java.util.ArrayList;
import java.util.List;
import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
public class DbHelper extends SQLiteOpenHelper {
    private static final int DATABASE_VERSION = 1;
    // Database Name
    private static final String DATABASE_NAME = "dbms";
    // tasks table name
    private static final String TABLE_QUEST = "quest";
    // tasks Table Columns names
    private static final String KEY_ID = "id";
    private static final String KEY_QUES = "question";
    private static final String KEY_ANSWER = "answer"; //correct option
    private static final String KEY_OPTA= "opta"; //option a
    private static final String KEY_OPTB= "optb"; //option b
    private static final String KEY_OPTC= "optc"; //option c
    private static final String KEY_OPTD= "optd"; //option d
    private SQLiteDatabase dbase;
    public DbHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }
    @Override
    public void onCreate(SQLiteDatabase db) {
        dbase=db;
        String sql = "CREATE TABLE IF NOT EXISTS " + TABLE_QUEST + " ( "
                + KEY_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " + KEY_QUES
                + " TEXT, " + KEY_ANSWER+ " TEXT, "+KEY_OPTA +" TEXT, "
                +KEY_OPTB +" TEXT, "+KEY_OPTC +" TEXT, "+KEY_OPTD+" TEXT)";
        db.execSQL(sql);
        addQuestions();
        //db.close();
    }
    private void addQuestions()
    {
		/*
		Question q1=new Question("the variable which can be accessed by all modules in a program, are know as?","d", "local variables", "internal variables", "external variables", "global variables");
		this.addQuestion(q1);
		Question q2=new Question("In what kind of storage structure for strings, one can easily insert, delete, concatenate and rearrange substrings??","c", "fixed length storage structure", "viriable length storage with fixed maximum", "linked list storage", "array type storage");
		this.addQuestion(q2);
		Question q3=new Question("which of the following operations is performed more efficiently by doubly linked list than by linear linked list??","a", "deleting a node whose location is given", "searhing an unsorted list for a given item", "inserting a node after the node with a given lcation", "traversing the list to process each node.");
		this.addQuestion(q3);
		Question q4=new Question("A linear list elements in which deletion can be done from one end (front) and insertion can take place only at the other end (rear) is known as?","a", "queues", "stacks", "tree", "queue");
		this.addQuestion(q4);
		Question q5=new Question("A linear list in which elements can be added or removed at either end but not in the middle is known as?","b", "queue", "deque", "stack", "tree");
		this.addQuestion(q5);
		*/

        Question q1=new Question("In LISP, the function returns the list that results after the first element is removed (the rest f the list), is","d", "car", "last", "cons", "cdr");
        this.addQuestion(q1);

        Question q2=new Question("Output segments of Artificial Intelligence programming contain(s)","d", "Printed language and synthesized speech", "Manipulation of physical object", "Locomotion", "All of the mentioned");
        this.addQuestion(q2);

        Question q3=new Question("LISP was created by:","a", "John McCarthy", "Marvin Minsky", "Alan Turing", "Allen Newell and Herbert Simon");
        this.addQuestion(q3);

        Question q4=new Question("Expert Ease was developed under the direction of:","b", "John McCarthy", "Donald Michie", "Lofti Zadeh", "Alan Turing");
        this.addQuestion(q4);

        Question q5=new Question("An Artificial Intelligence system developed by Terry A. Winograd to permit an interactive dialogue about a domain he called blocks-world","a", "SHRDLU", "SIMD", "BACON", "STUDENT");
        this.addQuestion(q5);

        Question q6=new Question("MLMenu, a natural language interface for the TI Explorer, is similar to:","b", "Ethernet", "NaturalLink", "PROLOG", "The Personal Consultant");
        this.addQuestion(q6);

        Question q7=new Question("Strong Artificial Intelligence is","a", "the embodiment of human intellectual capabilities within a computer", "a set of computer programs that produce output that would be considered to reflect intelligence if it were generated by humans", "the study of mental faculties through the use of mental models implemented on a computer", "all of the mentioned");
        this.addQuestion(q7);

        Question q8=new Question("The traditional way to exit and LISP system is to enter","a", "quit", "exit", "bye", "ok");
        this.addQuestion(q8);

        Question q9=new Question("In which of the following situations might a blind search be acceptable?","c", "real-life situation", "complex ", "small search space", "all of the mentioned");
        this.addQuestion(q9);

        Question q10=new Question("What is Artificial intelligence?","c", "Putting your intelligence into Computer", "Programming with your own intelligence", "Making a Machine intelligent", "Playing a Game");
        this.addQuestion(q10);

        Question q11=new Question("Which search method takes less memory?","a", "Depth-First Search", "Breadth-First search ", "Optimal search", "Linear Search");
        this.addQuestion(q11);

        Question q12=new Question("A heuristic is a way of trying","d", "To discover something or an idea embedded in a program", "To search and measure how far a node in a search tree seems to be from a goal", "To compare two nodes in a search tree to see if one is better than the other is", "All of the mentioned");
        this.addQuestion(q12);

        Question q13=new Question("How do you represent “All dogs have tails”?","a", "۷x: dog(x) àhastail(x)", "۷x: dog(x) àhastail(y)", "۷x: dog(y) àhastail(x)", "۷x: dog(x) àhasàtail(x)");
        this.addQuestion(q13);

        Question q14=new Question("A series of Artificial Intelligence systems, developed by Pat Langley to explore the role of heuristics in scientific discovery is ________","b", "RAMD", "BACON", "MIT", "DU");
        this.addQuestion(q14);

        Question q15=new Question("A.M. turing developed a technique for determining whether a computer could or could not demonstrate the artificial Intelligence, Presently, this technique is called","a", "Turing Test", "Algorithm", "Boolean Algebra", "Logarithm");
        this.addQuestion(q15);

        Question q16=new Question("A Personal Consultant knowledge base contain information in the form of:","d", "parameters", "contexts", "production rules", "all of the mentioned");
        this.addQuestion(q16);

        Question q17=new Question("Which approach to speech recognition avoids the problem caused by the variation in speech patterns among different speakers?","d", "Continuous speech recognition", "Isolated word recognition", "Connected word recognition", "Speaker-dependent recognition");
        this.addQuestion(q17);

        Question q18=new Question("A computer vision technique that relies on image templates is:","c", "edge detection", "binocular vision", "model-based vision", "robot vision");
        this.addQuestion(q18);

        Question q19=new Question("DARPA, the agency that has funded a great deal of American Artificial Intelligence research, is part of the Department of:","a", "Defense", "Energy", "Education", "Justice");
        this.addQuestion(q19);

        Question q20=new Question("Which of these schools was not among the early leaders in Artificial Intelligence research?","b", "Dartmouth University", "Harvard University", "Massachusetts Institute of Technology", "Stanford University");
        this.addQuestion(q20);

        Question q21=new Question("A certain Professor at the Stanford University coined the word ‘artificial intelligence’ in 1956 at a conference held at Dartmouth college. Can you name the Professor?","b", "David Levy", "John McCarthy", "Joseph Weizenbaum", "Hans Berliner");
        this.addQuestion(q21);

        Question q22=new Question("In LISP, the function (copy-list <list>)","a", "returns a new list that is equal to <list> by copying the top-level element of <list>", "returns the length of <list>", "returns t if <list> is empty", "all of the mentioned");
        this.addQuestion(q22);

        Question q23=new Question("Who is the “father” of artificial intelligence?","a", "Fisher Ada", "John McCarthy", "Allen Newell", "Alan Turning");
        this.addQuestion(q23);

        Question q24=new Question("In 1985, the famous chess player David Levy beat a world champion chess program in four straight games by using orthodox moves that confused the program. What was the name of the chess program?","b", "Kaissa", "CRAY BLITZ", "Golf", "DIGDUG");
        this.addQuestion(q24);

        Question q25=new Question("The explanation facility of an expert system may be used to:","d", "construct a diagnostic model", "expedite the debugging process", "explain the system’s reasoning process", "expedite the debugging process & explain the system’s reasoning process");
        this.addQuestion(q25);

        Question q26=new Question("A process that is repeated, evaluated, and refined is called:","d", "diagnostic", "descriptive", "interpretive", "iterative");
        this.addQuestion(q26);

        Question q27=new Question("Visual clues that are helpful in computer vision include:","d", "color and motion", "depth and texture", "height and weight", "color and motion, depth and texture");
        this.addQuestion(q27);

        Question q28=new Question("1. The conference that launched the AI revolution in 1956 was held at:","a", "Dartmouth", "Harvard", "New York", "Stanford");
        this.addQuestion(q28);

        Question q29=new Question("Texas Instruments Incorporated produces a low-cost LISP machine called:","b", "The Computer-Based Consultant", "The Explorer", "Smalltalk", "The Personal Consultant");
        this.addQuestion(q29);

        Question q30=new Question("When a top-level function is entered, the LISP processor do(es)","d", "It reads the function entered", "It evaluates the function and the function’s operands", "It prints the results returned by the function", "All of the mentioned");
        this.addQuestion(q30);

        Question q31=new Question("One method of programming a computer to exhibit human intelligence is called modeling or:","a", "simulation", "cognitization", "duplication", "psychic amelioration");
        this.addQuestion(q31);

        Question q32=new Question("Graphic interfaces were first used in a Xerox product called:","c", "InterLISP", "Ethernet", "Smalltalk", "ZetaLISP");
        this.addQuestion(q32);

        Question q33=new Question("The Al researcher who co-authored both the Handbook of Artificial Intelligence and The Fifth Generation is:","a", "Bruce Lee", "Randy Davis", "Ed Feigenbaum", "Mark Fox");
        this.addQuestion(q33);

        Question q34=new Question("Which of the following is being investigated as a means of automating the creation of a knowledge base?","d", "automatic knowledge acquisition", "simpler tools", "discovery of new concepts", "all of the mentioned");
        this.addQuestion(q34);

        Question q35=new Question("The CAI (Computer-Assisted Instruction) technique based on programmed instruction is:","a", "frame-based CAI", "generative CAI", "problem-solving CAI", "intelligent CAI");
        this.addQuestion(q35);

        Question q36=new Question("A robot’s “arm” is also known as its:","c", "end effector", "actuator", "manipulator ", "servomechanism");
        this.addQuestion(q36);

        Question q37=new Question("KEE is a product of:","b", "Teknowledge", "IntelliCorpn", "Texas Instruments", "Tech knowledge");
        this.addQuestion(q37);

        Question q38=new Question("In LISP, the function X (x). (2x+l) would be rendered as","a", "(lambda (x) (+(*2 x)l))", "(lambda (x) (+1 (* 2x)", "(+ lambda (x) 1 (*2x))", "(* lambda(x) (+2×1)");
        this.addQuestion(q38);

        Question q39=new Question("A natural language generation program must decide:","d", "what to say", "when to say something", "why it is being used", "both what to say & when to say something");
        this.addQuestion(q39);

        Question q40=new Question("In which of the following areas may ICAI programs prove to be useful?","a", "educational institutions", "corporations", "department of Defense", "all of the mentioned");
        this.addQuestion(q40);

        Question q41=new Question("A network with named nodes and labeled arcs that can be used to represent certain natural language grammars to facilitate parsing.","c", "Tree Network", "Star Network", "Transition Network", "Complete Network");
        this.addQuestion(q41);

        Question q42=new Question("Which of the following is true related to ‘Satisfiable’ property?","b", "A statement is satisfiable if there is some interpretation for which it is false", "A statement is satisfiable if there is some interpretation for which it is true", "A statement is satisfiable if there is no interpretation for which it is true", "A statement is satisfiable if there is no interpretation for which it is false");
        this.addQuestion(q42);

        Question q43=new Question("Two literals are complementary if","c", "They are equal", "They are identical and of equal sign", "They are identical but of opposite sign", "They are unequal but of equal sign");
        this.addQuestion(q43);

        Question q44=new Question("Consider a good system for the representation of knowledge in a particular domain. What property should it possess?","d", "Representational Adequacy", "Inferential Adequacy", "Inferential Efficiency", "All of the mentioned");
        this.addQuestion(q44);

        Question q45=new Question(" What is Transposition rule?","d", "From P → Q, infer ~Q → P", "From P → Q, infer Q → ~P", "From P → Q, infer Q → P", "From P → Q, infer ~Q → ~P");
        this.addQuestion(q45);

        Question q46=new Question("Third component of a planning system is to","a", "Detect when a solution has been found", "Detect when solution will be found", "Detect whether solution exists or not", "Detect whether multiple solutions exist");
        this.addQuestion(q46);

        Question q47=new Question("Which of the following is true in Statistical reasoning?","a", "The representation is extended to allow some kind of numeric measure of certainty to be associated with each statement", "The representation is extended to allow ‘TRUE or FALSE’ to be associated with each statement", "The representation is extended to allow some kind of numeric measure of certainty to be associated common to all statements", "The representation is extended to allow ‘TRUE or FALSE’ to be associated common to all statements");
        this.addQuestion(q47);

        Question q48=new Question("In default logic, we allow inference rules of the form","a", "(A : B) / C", "A / (B : C)", "A / B", "A / B : C");
        this.addQuestion(q48);

        Question q49=new Question("In Bayes theorem, what is the meant by P(Hi|E)?","a", "The probability that hypotheses Hi is true given evidence E", "The probability that hypotheses Hi is false given evidence E", "The probability that hypotheses Hi is true given false evidence E", "The probability that hypotheses Hi is false given false evidence E");
        this.addQuestion(q49);

        Question q50=new Question("Default reasoning is another type of","d", "Monotonic reasoning", "Analogical reasoning", "Bitonic reasoning", "Non-monotonic reasoning");
        this.addQuestion(q50);

        Question q51=new Question("Generality is the measure of","a", "Ease with which the method can be adapted to different domains of application", "The average time required to construct the target knowledge structures from some specified initial structures", "A learning system to function with unreliable feedback and with a variety of training examples", "The overall power of the system");
        this.addQuestion(q51);

        Question q52=new Question("The performance of an agent can be improved by","b", "Learning", "Observing", "Perceiving", "None of the mentioned");
        this.addQuestion(q52);

        Question q53=new Question("Two literals are complementary if","c", "They are equal", "They are identical and of equal sign", "They are identical but of opposite sign", "They are unequal but of equal sign");
        this.addQuestion(q53);

        Question q54=new Question("Consider a good system for the representation of knowledge in a particular domain. What property should it possess?","d", "Representational Adequacy", "Inferential Adequacy", "Inferential Efficiency", "All of the mentioned");
        this.addQuestion(q54);

        Question q55=new Question("What is Transposition rule?","a", "From P → Q, infer ~Q → P", "From P → Q, infer Q → ~P", "From P → Q, infer Q → P", "From P → Q, infer ~Q → ~P");
        this.addQuestion(q55);

        Question q56=new Question("Third component of a planning system is to","a", "Detect when a solution has been found", "Detect when solution will be found", "Detect whether solution exists or not", "Detect whether multiple solutions exist");
        this.addQuestion(q56);

        Question q57=new Question("Which of the following is true in Statistical reasoning?","a", "The representation is extended to allow some kind of numeric measure of certainty to be associated with each statement", "The representation is extended to allow ‘TRUE or FALSE’ to be associated with each statement", "The representation is extended to allow some kind of numeric measure of certainty to be associated common to all statements", "The representation is extended to allow ‘TRUE or FALSE’ to be associated common to all statements");
        this.addQuestion(q57);

        Question q58=new Question("In default logic, we allow inference rules of the form","a", " (A : B) / C", "A / (B : C)", "A / B", "A / B : C");
        this.addQuestion(q58);

        Question q59=new Question("In Bayes theorem, what is the meant by P(Hi|E)?","a", "The probability that hypotheses Hi is true given evidence E", "The probability that hypotheses Hi is false given evidence E", "The probability that hypotheses Hi is true given false evidence E", "The probability that hypotheses Hi is false given false evidence E");
        this.addQuestion(q59);

        Question q60=new Question("Default reasoning is another type of","d", "Monotonic reasoning", "Analogical reasoning", "Bitonic reasoning", "Non-monotonic reasoning");
        this.addQuestion(q60);

        Question q61=new Question("Generality is the measure of","a", "Ease with which the method can be adapted to different domains of application", "The average time required to construct the target knowledge structures from some specified initial structures", "A learning system to function with unreliable feedback and with a variety of training examples", "The overall power of the system");
        this.addQuestion(q61);

        Question q62=new Question("When talking to a speech recognition program, the program divides each second of your speech into 100 separate:","c", "Codes", "Phonemes", "Samples", "Words");
        this.addQuestion(q62);

        Question q63=new Question("Which term is used for describing the judgmental or commonsense part of problem solving?","a", "Heuristic", "Critical", "Value based", "Analytical");
        this.addQuestion(q63);

        Question q64=new Question("Which stage of the manufacturing process has been described as “the mapping of function onto form”?","a", "Design", "Distribution", "Project management", "Field service");
        this.addQuestion(q64);

        Question q65=new Question("Which kind of planning consists of successive representations of different levels of a plan?","a", "hierarchical planning", "non-hierarchical planning", "all of the mentioned", "project planning");
        this.addQuestion(q65);

        Question q66=new Question("What was originally called the “imitation game” by its creator?","a", "The Turing Test", "LISP", "The Logic Theorist", "Cybernetics");
        this.addQuestion(q66);

        Question q67=new Question("Decision support programs are designed to help managers make:","c", "budget projections", "visual presentations", "business decisions", "vacation schedules");
        this.addQuestion(q67);

        Question q68=new Question("PROLOG is an AI programming language, which solves problems with a form of symbolic logic known as predicate calculus. It was developed in 1972 at the University of Marseilles by a team of specialists. Can you name the person who headed this team?","a", "Alain Colmerauer", "Niklaus Wirth", "Seymour Papert", "John McCarthy");
        this.addQuestion(q68);

        Question q69=new Question("Programming a robot by physically moving it through the trajectory you want it to follow be called:","b", "contact sensing control", "continuous-path control", "robot vision control", "pick-and-place control");
        this.addQuestion(q69);

        Question q70=new Question("To invoke the LISP system, you must enter","b", "AI", "LISP", "CL (Common Lisp)", "Both LISP and CL");
        this.addQuestion(q70);

        Question q71=new Question("In LISP, the function (list-length <list>)","b", "returns a new list that is equal to &lt:list> by copying the top-level element of <list>", "returns the length of <list>", "returns t if <list> is empty", "all of the mentioned");
        this.addQuestion(q71);

        Question q72=new Question("ART (Automatic Reasoning Tool) is designed to be used on:","a", "LISP machines", "Personal computers", "Microcomputers", "All of the mentioned");
        this.addQuestion(q72);

        Question q73=new Question("Which particular generation of computers is associated with artificial intelligence?","c", "Second", "Fourth", "Fifth", "Third");
        this.addQuestion(q73);

        Question q74=new Question("Shaping teaching techniques to fit the learning patterns of individual students is the goal of:","c", "decision support", "automatic programming", "intelligent computer-assisted instruction", "expert systems");
        this.addQuestion(q74);

        Question q75=new Question("Which of the following function returns t If the object is a symbol m LISP?","b", "(* <object>)", "(symbolp <object>)", "(nonnumeric <object>)", "(constantp <object>)");
        this.addQuestion(q75);

        Question q76=new Question("The symbols used in describing the syntax of a programming language are","d", "0", "{}", "“”", "<>");
        this.addQuestion(q76);

        Question q77=new Question("Ambiguity may be caused by:","d", "syntactic ambiguity", "multiple word meanings", "unclear antecedents", "all of the mentioned");
        this.addQuestion(q77);

        Question q78=new Question("Which company offers the LISP machine considered “the most powerful symbolic processor available”?","b", "LMI", "Symbolics", "Xerox", "Texas Instruments");
        this.addQuestion(q78);

        Question q79=new Question("What of the following is considered a pivotal event in the history of Artificial Intelligence?","c", "1949, Donald O, The organization of Behavior", "1950, Computing Machinery and Intelligence", "1956, Dartmouth University Conference Organized by John McCarthy", "1961, Computer and Computer Sense");
        this.addQuestion(q79);

        Question q80=new Question("Natural language processing is divided into the two subfields of:","c", "symbolic and numeric", "time and motion", "algorithmic and heuristic", "understanding and generation");
        this.addQuestion(q80);

        Question q81=new Question("High-resolution, bit-mapped displays are useful for displaying:","c", "clearer characters", "graphics", "more characters", "all of the mentioned");
        this.addQuestion(q81);

        Question q82=new Question("A bidirectional feedback loop links computer modeling with:","c", "artificial science", "heuristic processing", "human intelligence", "cognitive science");
        this.addQuestion(q82);

        Question q83=new Question("Which of the following have people traditionally done better than computers?","c", "recognizing relative importance", "finding similarities", "resolving ambiguity", "all of the mentioned");
        this.addQuestion(q83);

        Question q84=new Question("In LISP, the function evaluates both and is","a", "set", "setq", "add", "eva");
        this.addQuestion(q84);

        Question q85=new Question("Which type of actuator generates a good deal of power but tends to be messy?","b", "electric", "hydraulic", "pneumatic", "both hydraulic & pneumatic");
        this.addQuestion(q85);

        Question q86=new Question("Research scientists all over the world are taking steps towards building computers with circuits patterned after the complex interconnections existing among the human brain’s nerve cells. What name is given to such type of computers?","c", "Intelligent computers", "Supercomputers", "Neural network computers", "Smart computers");
        this.addQuestion(q86);

        Question q87=new Question("The integrated circuit was invented by Jack Kilby of:","b", "MIT", "Texas Instruments", "Xerox", "All of the mentioned");
        this.addQuestion(q87);

        Question q88=new Question("People overcome natural language problems by:","d", "grouping attributes into frames", "understanding ideas in context", "identifying with familiar situations", "both understanding ideas in context & identifying with familiar situations");
        this.addQuestion(q88);

        Question q89=new Question("The Cedar, BBN Butterfly, Cosmic Cube and Hypercube machine can be characterized as","b", "SISD ", "MIMD ", "SIMD", "MISD");
        this.addQuestion(q89);

        Question q90=new Question("A series of AI systems, developed by Pat Langley to explore the role of heuristics in scientific discovery is ________","b", "RAMD", "BACON", "MIT", "DU");
        this.addQuestion(q90);

        Question q91=new Question("The primary interactive method of communication used by humans is:","c", "reading", "writing ", "speaking ", "all of the mentioned");
        this.addQuestion(q91);

        Question q92=new Question("Elementary linguistic units which are smaller than words are:","d", "allophones", "phonemes", "syllables", "all of the mentioned");
        this.addQuestion(q92);

        Question q93=new Question("In LISP, the atom that stands for “true” is","a", "t", "ml", "y", "time");
        this.addQuestion(q93);

        Question q94=new Question("A mouse device may be","d", "electro-chemical", "mechanical", "optical", "both mechanical and optical");
        this.addQuestion(q94);

        Question q95=new Question("An expert system differs from a database program in that only an expert system:","b", "contains declarative knowledge", "contains procedural knowledge", "features the retrieval of stored information", "expects users to draw their own conclusions");
        this.addQuestion(q95);

        Question q96=new Question("Arthur Samuel is linked inextricably with a program that played:","a", "checkers", "chess", "cricket", "football");
        this.addQuestion(q96);

        Question q97=new Question("Natural language understanding is used in:","d", "natural language interfaces", "natural language front ends", "text understanding systems", "all of the mentioned");
        this.addQuestion(q97);

        Question q98=new Question("Which of the following are examples of software development tools?","d", "debuggers", "editors", "assemblers, compilers and interpreters", "all of the mentioned");
        this.addQuestion(q98);

        Question q99=new Question(" The first AI programming language was called:","d", "BASIC", "FORTRAN", "IPL(Inductive logic programming)", "LISP");
        this.addQuestion(q99);

        Question q100=new Question("The Personal Consultant is based on:","d", "EMYCIN", "OPS5+", "XCON", "All of the mentioned");
        this.addQuestion(q100);




    }
    @Override
    public void onUpgrade(SQLiteDatabase db, int oldV, int newV) {
        // Drop older table if existed
        db.execSQL("DROP TABLE IF EXISTS " + TABLE_QUEST);
        // Create tables again
        onCreate(db);
    }
    // Adding new question
    public void addQuestion(Question quest) {
        //SQLiteDatabase db = this.getWritableDatabase();
        ContentValues values = new ContentValues();
        values.put(KEY_QUES, quest.getQUESTION());
        values.put(KEY_ANSWER, quest.getANSWER());
        values.put(KEY_OPTA, quest.getOPTA());
        values.put(KEY_OPTB, quest.getOPTB());
        values.put(KEY_OPTC, quest.getOPTC());
        values.put(KEY_OPTD, quest.getOPTD());
        // Inserting Row
        dbase.insert(TABLE_QUEST, null, values);
    }
    public List<Question> getAllQuestions() {
        List<Question> quesList = new ArrayList<Question>();
        // Select All Query
        String selectQuery = "SELECT  * FROM " + TABLE_QUEST;
        dbase=this.getReadableDatabase();
        Cursor cursor = dbase.rawQuery(selectQuery, null);
        // looping through all rows and adding to list
        if (cursor.moveToFirst()) {
            do {
                Question quest = new Question();
                quest.setID(cursor.getInt(0));
                quest.setQUESTION(cursor.getString(1));
                quest.setANSWER(cursor.getString(2));
                quest.setOPTA(cursor.getString(3));
                quest.setOPTB(cursor.getString(4));
                quest.setOPTC(cursor.getString(5));
                quest.setOPTD(cursor.getString(6));
                quesList.add(quest);
            } while (cursor.moveToNext());
        }
        // return quest list
        return quesList;
    }
    public int rowcount()
    {
        int row=0;
        String selectQuery = "SELECT  * FROM " + TABLE_QUEST;
        SQLiteDatabase db = this.getWritableDatabase();
        Cursor cursor = db.rawQuery(selectQuery, null);
        row=cursor.getCount();
        return row;
    }
}
